//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_SkinWeightsWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.SkinWeights));
		L.RegConstant("OneBone", UnityEngine.SkinWeights.OneBone);
		L.RegConstant("TwoBones", UnityEngine.SkinWeights.TwoBones);
		L.RegConstant("FourBones", UnityEngine.SkinWeights.FourBones);
		L.RegConstant("Unlimited", UnityEngine.SkinWeights.Unlimited);
		L.EndEnum();
		TypeTraits<UnityEngine.SkinWeights>.Check = CheckType;
		StackTraits<UnityEngine.SkinWeights>.Push = Push;
	}

	static void Push(IntPtr L, UnityEngine.SkinWeights arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(UnityEngine.SkinWeights), L, pos);
	}
}

