-- Generated by CSharp.lua Compiler
local System = System
local UnityEngine = UnityEngine
System.namespace("", function (namespace)
  namespace.class("aaa", function (namespace)
    local Start, printa, Update, class
    Start = function (this)
      UnityEngine.Debug.Log("廷廷廷！")
    end
    printa = function (this)
      UnityEngine.Debug.Log(class.a .. "调用方法")
    end
    Update = function (this)
      --Debug.Log(Settings.Paths.CompiledOutDir);
    end
    class = {
      base = function (out)
        return {
          out.UnityEngine.MonoBehaviour
        }
      end,
      a = "姚雨廷",
      Start = Start,
      printa = printa,
      Update = Update
    }
    return class
  end)
end)
