-- Generated by CSharp.lua Compiler
return function (path)
  return System.init({
    path = path,
    files = {
      "aaa",
      "test"
    },
    types = {
      "aaa",
      "test"
    }
  })
end
