-- Generated by CSharp.lua Compiler
local System = System
local UnityEngine = UnityEngine
System.namespace("", function (namespace)
  namespace.class("test", function (namespace)
    local Start, Update
    Start = function (this)
      UnityEngine.Debug.Log("姚姚姚姚！")
      --PanelManager.Init();
      --PanelManager.Open<TipPanel>("廷廷廷！");
      local go = UnityEngine.GameObject()
      go:setname("雨雨雨雨雨")
      go:AddComponent(aaa)
      go:GetComponent(aaa):printa()
      UnityEngine.Debug.Log(aaa.a)
    end
    Update = function (this)
    end
    return {
      base = function (out)
        return {
          out.UnityEngine.MonoBehaviour
        }
      end,
      Start = Start,
      Update = Update
    }
  end)
end)
