// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: Demo/Proto/game.proto

package Proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MsgGetPlayerIntroduction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerIntroduction string `protobuf:"bytes,1,opt,name=playerIntroduction,proto3" json:"playerIntroduction,omitempty"`
}

func (x *MsgGetPlayerIntroduction) Reset() {
	*x = MsgGetPlayerIntroduction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Demo_Proto_game_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgGetPlayerIntroduction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgGetPlayerIntroduction) ProtoMessage() {}

func (x *MsgGetPlayerIntroduction) ProtoReflect() protoreflect.Message {
	mi := &file_Demo_Proto_game_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgGetPlayerIntroduction.ProtoReflect.Descriptor instead.
func (*MsgGetPlayerIntroduction) Descriptor() ([]byte, []int) {
	return file_Demo_Proto_game_proto_rawDescGZIP(), []int{0}
}

func (x *MsgGetPlayerIntroduction) GetPlayerIntroduction() string {
	if x != nil {
		return x.PlayerIntroduction
	}
	return ""
}

type MsgSavePlayerIntroduction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerIntroduction string `protobuf:"bytes,1,opt,name=playerIntroduction,proto3" json:"playerIntroduction,omitempty"`
	Result             int32  `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *MsgSavePlayerIntroduction) Reset() {
	*x = MsgSavePlayerIntroduction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Demo_Proto_game_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgSavePlayerIntroduction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSavePlayerIntroduction) ProtoMessage() {}

func (x *MsgSavePlayerIntroduction) ProtoReflect() protoreflect.Message {
	mi := &file_Demo_Proto_game_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSavePlayerIntroduction.ProtoReflect.Descriptor instead.
func (*MsgSavePlayerIntroduction) Descriptor() ([]byte, []int) {
	return file_Demo_Proto_game_proto_rawDescGZIP(), []int{1}
}

func (x *MsgSavePlayerIntroduction) GetPlayerIntroduction() string {
	if x != nil {
		return x.PlayerIntroduction
	}
	return ""
}

func (x *MsgSavePlayerIntroduction) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type MsgGetHeadPhoto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeadPhoto int32 `protobuf:"varint,1,opt,name=headPhoto,proto3" json:"headPhoto,omitempty"`
}

func (x *MsgGetHeadPhoto) Reset() {
	*x = MsgGetHeadPhoto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Demo_Proto_game_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgGetHeadPhoto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgGetHeadPhoto) ProtoMessage() {}

func (x *MsgGetHeadPhoto) ProtoReflect() protoreflect.Message {
	mi := &file_Demo_Proto_game_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgGetHeadPhoto.ProtoReflect.Descriptor instead.
func (*MsgGetHeadPhoto) Descriptor() ([]byte, []int) {
	return file_Demo_Proto_game_proto_rawDescGZIP(), []int{2}
}

func (x *MsgGetHeadPhoto) GetHeadPhoto() int32 {
	if x != nil {
		return x.HeadPhoto
	}
	return 0
}

type MsgSaveHeadPhoto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeadPhoto int32 `protobuf:"varint,1,opt,name=headPhoto,proto3" json:"headPhoto,omitempty"`
	Result    int32 `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *MsgSaveHeadPhoto) Reset() {
	*x = MsgSaveHeadPhoto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Demo_Proto_game_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgSaveHeadPhoto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSaveHeadPhoto) ProtoMessage() {}

func (x *MsgSaveHeadPhoto) ProtoReflect() protoreflect.Message {
	mi := &file_Demo_Proto_game_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSaveHeadPhoto.ProtoReflect.Descriptor instead.
func (*MsgSaveHeadPhoto) Descriptor() ([]byte, []int) {
	return file_Demo_Proto_game_proto_rawDescGZIP(), []int{3}
}

func (x *MsgSaveHeadPhoto) GetHeadPhoto() int32 {
	if x != nil {
		return x.HeadPhoto
	}
	return 0
}

func (x *MsgSaveHeadPhoto) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type MsgSendMessageToWord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Id      string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Result  int32  `protobuf:"varint,3,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *MsgSendMessageToWord) Reset() {
	*x = MsgSendMessageToWord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Demo_Proto_game_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgSendMessageToWord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSendMessageToWord) ProtoMessage() {}

func (x *MsgSendMessageToWord) ProtoReflect() protoreflect.Message {
	mi := &file_Demo_Proto_game_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSendMessageToWord.ProtoReflect.Descriptor instead.
func (*MsgSendMessageToWord) Descriptor() ([]byte, []int) {
	return file_Demo_Proto_game_proto_rawDescGZIP(), []int{4}
}

func (x *MsgSendMessageToWord) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MsgSendMessageToWord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MsgSendMessageToWord) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type MsgSendMessageToFriend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message  string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Id       string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	FriendId string `protobuf:"bytes,3,opt,name=friendId,proto3" json:"friendId,omitempty"`
	Result   int32  `protobuf:"varint,4,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *MsgSendMessageToFriend) Reset() {
	*x = MsgSendMessageToFriend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Demo_Proto_game_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgSendMessageToFriend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSendMessageToFriend) ProtoMessage() {}

func (x *MsgSendMessageToFriend) ProtoReflect() protoreflect.Message {
	mi := &file_Demo_Proto_game_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSendMessageToFriend.ProtoReflect.Descriptor instead.
func (*MsgSendMessageToFriend) Descriptor() ([]byte, []int) {
	return file_Demo_Proto_game_proto_rawDescGZIP(), []int{5}
}

func (x *MsgSendMessageToFriend) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MsgSendMessageToFriend) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MsgSendMessageToFriend) GetFriendId() string {
	if x != nil {
		return x.FriendId
	}
	return ""
}

func (x *MsgSendMessageToFriend) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type MsgGetFriendList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FriendList string `protobuf:"bytes,1,opt,name=friendList,proto3" json:"friendList,omitempty"`
	Result     int32  `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *MsgGetFriendList) Reset() {
	*x = MsgGetFriendList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Demo_Proto_game_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgGetFriendList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgGetFriendList) ProtoMessage() {}

func (x *MsgGetFriendList) ProtoReflect() protoreflect.Message {
	mi := &file_Demo_Proto_game_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgGetFriendList.ProtoReflect.Descriptor instead.
func (*MsgGetFriendList) Descriptor() ([]byte, []int) {
	return file_Demo_Proto_game_proto_rawDescGZIP(), []int{6}
}

func (x *MsgGetFriendList) GetFriendList() string {
	if x != nil {
		return x.FriendList
	}
	return ""
}

func (x *MsgGetFriendList) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type MsgDeleteFriend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FriendId string `protobuf:"bytes,1,opt,name=friendId,proto3" json:"friendId,omitempty"`
	Id       string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Result   int32  `protobuf:"varint,3,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *MsgDeleteFriend) Reset() {
	*x = MsgDeleteFriend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Demo_Proto_game_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgDeleteFriend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgDeleteFriend) ProtoMessage() {}

func (x *MsgDeleteFriend) ProtoReflect() protoreflect.Message {
	mi := &file_Demo_Proto_game_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgDeleteFriend.ProtoReflect.Descriptor instead.
func (*MsgDeleteFriend) Descriptor() ([]byte, []int) {
	return file_Demo_Proto_game_proto_rawDescGZIP(), []int{7}
}

func (x *MsgDeleteFriend) GetFriendId() string {
	if x != nil {
		return x.FriendId
	}
	return ""
}

func (x *MsgDeleteFriend) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MsgDeleteFriend) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type MsgAddFriend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FriendId string `protobuf:"bytes,1,opt,name=friendId,proto3" json:"friendId,omitempty"`
	Id       string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Result   int32  `protobuf:"varint,3,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *MsgAddFriend) Reset() {
	*x = MsgAddFriend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Demo_Proto_game_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgAddFriend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgAddFriend) ProtoMessage() {}

func (x *MsgAddFriend) ProtoReflect() protoreflect.Message {
	mi := &file_Demo_Proto_game_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgAddFriend.ProtoReflect.Descriptor instead.
func (*MsgAddFriend) Descriptor() ([]byte, []int) {
	return file_Demo_Proto_game_proto_rawDescGZIP(), []int{8}
}

func (x *MsgAddFriend) GetFriendId() string {
	if x != nil {
		return x.FriendId
	}
	return ""
}

func (x *MsgAddFriend) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MsgAddFriend) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type MsgAcceptAddFriend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FriendId string `protobuf:"bytes,1,opt,name=friendId,proto3" json:"friendId,omitempty"`
	Id       string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Result   int32  `protobuf:"varint,3,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *MsgAcceptAddFriend) Reset() {
	*x = MsgAcceptAddFriend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Demo_Proto_game_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgAcceptAddFriend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgAcceptAddFriend) ProtoMessage() {}

func (x *MsgAcceptAddFriend) ProtoReflect() protoreflect.Message {
	mi := &file_Demo_Proto_game_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgAcceptAddFriend.ProtoReflect.Descriptor instead.
func (*MsgAcceptAddFriend) Descriptor() ([]byte, []int) {
	return file_Demo_Proto_game_proto_rawDescGZIP(), []int{9}
}

func (x *MsgAcceptAddFriend) GetFriendId() string {
	if x != nil {
		return x.FriendId
	}
	return ""
}

func (x *MsgAcceptAddFriend) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MsgAcceptAddFriend) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_Demo_Proto_game_proto protoreflect.FileDescriptor

var file_Demo_Proto_game_proto_rawDesc = []byte{
	0x0a, 0x15, 0x44, 0x65, 0x6d, 0x6f, 0x2f, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x6d,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x22, 0x4a, 0x0a,
	0x18, 0x4d, 0x73, 0x67, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x74,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x12, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x74,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x63, 0x0a, 0x19, 0x4d, 0x73, 0x67,
	0x53, 0x61, 0x76, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x12, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x49, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x12, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x2f,
	0x0a, 0x0f, 0x4d, 0x73, 0x67, 0x47, 0x65, 0x74, 0x48, 0x65, 0x61, 0x64, 0x50, 0x68, 0x6f, 0x74,
	0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x68, 0x65, 0x61, 0x64, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x68, 0x65, 0x61, 0x64, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x22,
	0x48, 0x0a, 0x10, 0x4d, 0x73, 0x67, 0x53, 0x61, 0x76, 0x65, 0x48, 0x65, 0x61, 0x64, 0x50, 0x68,
	0x6f, 0x74, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x68, 0x65, 0x61, 0x64, 0x50, 0x68, 0x6f, 0x74, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x68, 0x65, 0x61, 0x64, 0x50, 0x68, 0x6f, 0x74,
	0x6f, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x58, 0x0a, 0x14, 0x4d, 0x73, 0x67,
	0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x57, 0x6f, 0x72,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x22, 0x76, 0x0a, 0x16, 0x4d, 0x73, 0x67, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x4a, 0x0a, 0x10, 0x4d,
	0x73, 0x67, 0x47, 0x65, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x1e, 0x0a, 0x0a, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x55, 0x0a, 0x0f, 0x4d, 0x73, 0x67, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x52,
	0x0a, 0x0c, 0x4d, 0x73, 0x67, 0x41, 0x64, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x22, 0x58, 0x0a, 0x12, 0x4d, 0x73, 0x67, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x41,
	0x64, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x0c, 0x5a, 0x0a,
	0x44, 0x65, 0x6d, 0x6f, 0x2f, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_Demo_Proto_game_proto_rawDescOnce sync.Once
	file_Demo_Proto_game_proto_rawDescData = file_Demo_Proto_game_proto_rawDesc
)

func file_Demo_Proto_game_proto_rawDescGZIP() []byte {
	file_Demo_Proto_game_proto_rawDescOnce.Do(func() {
		file_Demo_Proto_game_proto_rawDescData = protoimpl.X.CompressGZIP(file_Demo_Proto_game_proto_rawDescData)
	})
	return file_Demo_Proto_game_proto_rawDescData
}

var file_Demo_Proto_game_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_Demo_Proto_game_proto_goTypes = []interface{}{
	(*MsgGetPlayerIntroduction)(nil),  // 0: game.MsgGetPlayerIntroduction
	(*MsgSavePlayerIntroduction)(nil), // 1: game.MsgSavePlayerIntroduction
	(*MsgGetHeadPhoto)(nil),           // 2: game.MsgGetHeadPhoto
	(*MsgSaveHeadPhoto)(nil),          // 3: game.MsgSaveHeadPhoto
	(*MsgSendMessageToWord)(nil),      // 4: game.MsgSendMessageToWord
	(*MsgSendMessageToFriend)(nil),    // 5: game.MsgSendMessageToFriend
	(*MsgGetFriendList)(nil),          // 6: game.MsgGetFriendList
	(*MsgDeleteFriend)(nil),           // 7: game.MsgDeleteFriend
	(*MsgAddFriend)(nil),              // 8: game.MsgAddFriend
	(*MsgAcceptAddFriend)(nil),        // 9: game.MsgAcceptAddFriend
}
var file_Demo_Proto_game_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Demo_Proto_game_proto_init() }
func file_Demo_Proto_game_proto_init() {
	if File_Demo_Proto_game_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Demo_Proto_game_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgGetPlayerIntroduction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Demo_Proto_game_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgSavePlayerIntroduction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Demo_Proto_game_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgGetHeadPhoto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Demo_Proto_game_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgSaveHeadPhoto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Demo_Proto_game_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgSendMessageToWord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Demo_Proto_game_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgSendMessageToFriend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Demo_Proto_game_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgGetFriendList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Demo_Proto_game_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgDeleteFriend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Demo_Proto_game_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgAddFriend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Demo_Proto_game_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgAcceptAddFriend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Demo_Proto_game_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Demo_Proto_game_proto_goTypes,
		DependencyIndexes: file_Demo_Proto_game_proto_depIdxs,
		MessageInfos:      file_Demo_Proto_game_proto_msgTypes,
	}.Build()
	File_Demo_Proto_game_proto = out.File
	file_Demo_Proto_game_proto_rawDesc = nil
	file_Demo_Proto_game_proto_goTypes = nil
	file_Demo_Proto_game_proto_depIdxs = nil
}
